/**
 * Stamp a fresh build version so returning clients auto-refresh.
 *
 *   node scripts/gen-version.mjs
 *
 * Runs automatically before `npm run dev` / `npm run deploy` (see package.json).
 * The version is `<git-short-sha>.<build-epoch>` (falls back to `dev.<epoch>`
 * when git isn't available), and it is written to TWO places that must agree:
 *
 *   1. public/version.js  — an ES module imported by app.js and src/worker.js.
 *   2. public/sw.js       — the `CACHE` constant is rewritten to include it, so
 *                           every build invalidates the old app-shell cache.
 *
 * Because the Service Worker's cache name changes on every deploy, a new SW
 * installs → skipWaiting → activate → deletes stale caches → controllerchange,
 * and app.js reloads the page onto the new assets. This is what removes the old
 * need to hand-bump `king-chess-vN`.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PUBLIC = join(__dirname, '..', 'public');

function gitShortSha() {
  try {
    return execFileSync('git', ['rev-parse', '--short', 'HEAD'], {
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim();
  } catch {
    return 'dev';
  }
}

const version = `${gitShortSha()}.${Date.now()}`;

// 1. Emit the shared module.
writeFileSync(
  join(PUBLIC, 'version.js'),
  `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.\n` +
    `export const VERSION = ${JSON.stringify(version)};\n`,
);

// 2. Rewrite the Service Worker's cache name to match.
const swPath = join(PUBLIC, 'sw.js');
const sw = readFileSync(swPath, 'utf8');
const next = sw.replace(
  /const CACHE = 'king-chess-[^']*';/,
  `const CACHE = 'king-chess-${version}';`,
);
if (next === sw) {
  throw new Error("Couldn't find the CACHE constant to stamp in public/sw.js");
}
writeFileSync(swPath, next);

console.log('stamped version', version);
